export enum DamageType {
  Bludgeoning = "bludgeoning",
  Piercing = "piercing",
  Slashing = "slashing",
  Fire = "fire",
  Cold = "cold",
  Acid = "acid",
  Thunder = "thunder",
  Lightning = "lightning",
  Poison = "poison",
  Radiant = "radiant",
  Necrotic = "necrotic",
  Psychic = "psychic",
  Force = "force",
}
